Lesson2
kikutina/geekshop pull request #1
Opened 2020-12-05 14:09 UTC by kikutina

2020-12-08 08:12 UTC, Vokler requested changes

2020-12-08 08:12 UTC, vprinz commented on mainapp/views.py
> +    context = {
Добавьте сюда еще список продуктов, чтобы в файле products.html избавиться от повторяющих блоков из продуктов. То есть сделать блок из цикла for и генерировать его из контекста, созданного в этой функции

2020-12-10 13:25 UTC, kikutina commented on mainapp/views.py
> +    context = {
Добрый день! список продуктов добавлен. Проверьте. пожалуйста.

2020-12-12 12:38 UTC, Vokler approved these changes

2020-12-12 12:38 UTC, merged